development:
  smtp:
    address: 'smtp.gmail.com'
    port: 587
    domain: 'unmundodeovejitas.com.ar'
    authentication: 'plain'
    user_name: 'unmundodeovejitas@gmail.com'
    password: 'pass'
    enable_starttls_auto: true

  public_host: 'unmundodeovejitas.com.ar'
  public_domain: 'unmundodeovejitas.com.ar'
  page_title: 'Un Mundo De Ovejitas'

production:
  smtp:
    address: 'smtp.gmail.com'
    port: 587
    domain: 'unmundodeovejitas.com.ar'
    authentication: 'plain'
    user_name: 'unmundodeovejitas@gmail.com'
    password: 'pass'
    enable_starttls_auto: true

  public_host: 'unmundodeovejitas.com.ar'
  public_domain: 'unmundodeovejitas.com.ar'
  page_title: 'Un Mundo De Ovejitas'
