development:
  adapter: postgresql
  encoding: unicode
  database: store_dev
  pool: 5
  username: general_user
  password: 'general_user'
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: store_test
  pool: 5
  username: <%= ENV['TRAVIS'] ? 'postgres' : 'general_user' %>
  password: <%= ENV['TRAVIS'] ? '' : 'general_user' %>
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: store_prod
  pool: 5
  username: general_user
  password: 'general_user'
  host: localhost
